# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_gen/server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_gen/server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15grpc_gen/server.proto\"7\n\x11QuickMatchRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\x0c\"h\n\x0fQuickMatchReply\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06server\x18\x02 \x01(\t\x12\x10\n\x08\x61uth_key\x18\x03 \x01(\t\x12\x0f\n\x07ranking\x18\x04 \x01(\x01\x12\x10\n\x08response\x18\x05 \x01(\t2@\n\nMatchmaker\x12\x32\n\x08GetMatch\x12\x12.QuickMatchRequest\x1a\x10.QuickMatchReply\"\x00\x62\x06proto3')
)




_QUICKMATCHREQUEST = _descriptor.Descriptor(
  name='QuickMatchRequest',
  full_name='QuickMatchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='QuickMatchRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='QuickMatchRequest.password', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=80,
)


_QUICKMATCHREPLY = _descriptor.Descriptor(
  name='QuickMatchReply',
  full_name='QuickMatchReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='QuickMatchReply.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server', full_name='QuickMatchReply.server', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth_key', full_name='QuickMatchReply.auth_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ranking', full_name='QuickMatchReply.ranking', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='QuickMatchReply.response', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=186,
)

DESCRIPTOR.message_types_by_name['QuickMatchRequest'] = _QUICKMATCHREQUEST
DESCRIPTOR.message_types_by_name['QuickMatchReply'] = _QUICKMATCHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuickMatchRequest = _reflection.GeneratedProtocolMessageType('QuickMatchRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUICKMATCHREQUEST,
  __module__ = 'grpc_gen.server_pb2'
  # @@protoc_insertion_point(class_scope:QuickMatchRequest)
  ))
_sym_db.RegisterMessage(QuickMatchRequest)

QuickMatchReply = _reflection.GeneratedProtocolMessageType('QuickMatchReply', (_message.Message,), dict(
  DESCRIPTOR = _QUICKMATCHREPLY,
  __module__ = 'grpc_gen.server_pb2'
  # @@protoc_insertion_point(class_scope:QuickMatchReply)
  ))
_sym_db.RegisterMessage(QuickMatchReply)



_MATCHMAKER = _descriptor.ServiceDescriptor(
  name='Matchmaker',
  full_name='Matchmaker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=188,
  serialized_end=252,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMatch',
    full_name='Matchmaker.GetMatch',
    index=0,
    containing_service=None,
    input_type=_QUICKMATCHREQUEST,
    output_type=_QUICKMATCHREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATCHMAKER)

DESCRIPTOR.services_by_name['Matchmaker'] = _MATCHMAKER

# @@protoc_insertion_point(module_scope)
